### ISSUE TITLE
Missing DEPS on in functions.yaml for transitivity functions

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2217]
In `functions.yaml`, do these needs a `DEPS: vids ON graph`? @ntamas 

```
igraph_transitivity_undirected:
    PARAMS: GRAPH graph, OUT REAL res, TRANSITIVITY_MODE mode=NAN

igraph_transitivity_local_undirected:
    PARAMS: GRAPH graph, OUT VECTOR res, VERTEX_SELECTOR vids=ALL, TRANSITIVITY_MODE mode=NAN

igraph_transitivity_avglocal_undirected:
    PARAMS: GRAPH graph, OUT REAL res, TRANSITIVITY_MODE mode=NAN
```

**Comment by szhorvat** [comment]
I opened this as an issue because it serves to track these omissions in `functions.yaml`. I also wanted to have the explanation in a more permanent place than chat, so I can refer to it later.

I notice that some functions have an extra `res ON graph vids`, for example:

```yaml
igraph_closeness:
    PARAMS: |-
        GRAPH graph, OUT VERTEX_QTY res,
        OPTIONAL OUT VECTOR_INT reachable_count,
        OPTIONAL OUT BOOLEAN all_reachable,
        VERTEX_SELECTOR vids=ALL,
        NEIMODE mode=OUT, EDGEWEIGHTS weights=NULL,
        BOOLEAN normalized=False
    DEPS: vids ON graph, weights ON graph, res ON graph vids
```

Do we always want to have this `res ON graph vids`? Some functions don't have it:

```yaml
igraph_degree:
    PARAMS: |-
        GRAPH graph, OUT VECTOR_INT res, VERTEX_SELECTOR vids=ALL, NEIMODE mode=ALL,
        BOOLEAN loops
    DEPS: vids ON graph
```
