### ISSUE TITLE
Return in `functions.yaml`

### ISSUE THREAD

**Issue by mantielero** [igraph/igraph#2634]
https://github.com/igraph/igraph/blob/78228dc28e8b29daf8c66f021afc9b05336d55bd/interfaces/functions.yaml#L13

I was wondering if [functions.yaml](https://github.com/igraph/igraph/blob/master/interfaces/functions.yaml) should have something like:
```yaml
igraph_empty:
    PARAMS: OUT GRAPH graph, INTEGER n=0, BOOLEAN directed=True
    RETURN: ERROR   # <<< THIS LINE
```
givent that in accordance to [the header](https://github.com/igraph/igraph/blob/78228dc28e8b29daf8c66f021afc9b05336d55bd/include/igraph_interface.h#L39) it returns:
```c
igraph_error_t
```

If that is the case, then I believe many functions might be missing `RETURN: ERROR`.
